name: mem0-mcp
region: fra1
services:
  - name: api
    git:
      repo_clone_url: https://github.com/Sternberg-Corp-Projects/mem0.git
      branch: main
    source_dir: platform/api
    http_port: 8765
    instance_size_slug: basic-xxs
    envs:
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        value: ${OPENAI_API_KEY}
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: QDRANT_URL
        scope: RUN_TIME
        value: http://qdrant:6333
    routes:
      - path: /
    health_check:
      http_path: /health
  - name: ui
    git:
      repo_clone_url: https://github.com/Sternberg-Corp-Projects/mem0.git
      branch: main
    source_dir: platform/ui
    http_port: 3000
    
    envs:
      - key: NEXT_PUBLIC_API_URL
        scope: RUN_TIME
        value: ${api.PUBLIC_URL}
      - key: NEXT_PUBLIC_USER_ID
        scope: RUN_TIME
        value: sternberg_dev
    routes:
      - path: /ui
  - name: qdrant
    image:
      registry_type: DOCKER_HUB
      registry: docker.io
      repository: qdrant/qdrant
      tag: latest
    http_port: 6333
    i
    envs:
      - key: QDRANT__SERVICE__GRPC_PORT
        scope: RUN_TIME
        value: "6334"
    internal_ports:
      - 6333
databases:
  - name: db
    engine: PG
    version: "16"
    production: true
    
