name: mem0-mcp
region: fra1  # Change to your closest region, e.g., fra for Europe
services:
  - name: api
    github:
      repo: Sternberg-Corp-Projects/mem0  # Replace with your GitHub username/repo
      branch: main
    dockerfile_path: platform/api/Dockerfile
    http_port: 8765
    envs:
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}  # You'll set this in DigitalOcean later
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: QDRANT_URL
        value: http://qdrant:6333
    instance_size_slug: basic-xs  # Basic plan (~$5/month)
  - name: ui  # Optional for dashboard access
    github:
      repo: Sternberg-Corp-Projects/mem0
      branch: main
    dockerfile_path: platform/ui/Dockerfile
    http_port: 3000
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: ${api.HTTP_HOST}
      - key: NEXT_PUBLIC_USER_ID
        value: your_user_id  # Replace with a unique ID, e.g., global_dev
    instance_size_slug: basic-xs
  - name: qdrant
    image:
      registry_type: DOCKER_HUB
      repository: qdrant/qdrant
      tag: latest
    http_port: 6333
    instance_size_slug: basic-xs
databases:
  - name: db
    engine: PG  # Postgres
    production: true
    instance_size_slug: db-s-dev-database  # ~$7/month for dev